"""
ShiVi Offline Sync & Causal Engine API Router
=============================================

Briefing:
    Core synchronization router implementing ShiVi's bi-directional offline event-sourcing
    pipeline. Field responders capture incidents, route assessments, task updates, and photographic
    evidence entirely offline into local SQLite databases. When any network bearer becomes
    available (BLE mesh relay, Wi-Fi Direct, tactical hotspot, or cellular), the field device
    initiates a batch push/pull sequence.

Reason:
    In disaster response, network connectivity is intermittent, slow, and partitioned.
    Traditional REST APIs (direct POST/PUT on mutable resource endpoints) fail completely because:
    1. Simultaneous edits overwrite each other without a causal trace.
    2. Connection drops midway through requests cause duplicate records or partial state corruption.
    3. Low-bandwidth Bluetooth Low Energy (BLE) channels cannot handle large monolithic HTTP bodies.

Architectural Solutions in this Router:
    - Idempotent Event Push (`/push`): Evaluates unique `event_id` keys against the immutable event
      ledger, guaranteeing exactly-once semantics even across repeated network re-transmissions.
    - Causal Conflict Detection: Automatically detects concurrent contradictions on life-safety
      fields (e.g. USABLE vs BLOCKED), freezes entities into `UNCERTAIN` state, locks dependent
      tasks, and generates a formal `ConflictCase` for supervisor adjudication.
    - Cursor-Based Pull (`/pull`): Enables bandwidth-efficient, monotonic delta retrieval so nodes
      only download events received since their last synchronization checkpoint.
    - Omni-Bearer Mesh Packetization (`/mesh/packetize`, `/mesh/reassemble`): Slices arbitrary
      JSON payloads into ≤496-byte BLE 5.0 GATT MTU chunks with CRC32 checksums and reassembles them
      with full SHA-256 payload integrity validation.
"""

import uuid
import zlib
import base64
import json
import hashlib
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

from app.core.database import get_db
from app.core.security import get_current_user_token, TokenPayload
from app.modules.audit.models import OperationalEvent, AuditEntry
from app.modules.incidents.models import Incident, RouteObservation
from app.modules.tasks.models import Task
from app.modules.conflicts.models import ConflictCase

# Briefing: FastAPI router mounted under `/sync` tag for all offline replication workflows.
# Reason: Centralizes event-sourcing ingestion and mesh packetization endpoints.
router = APIRouter(prefix="/sync", tags=["Offline Sync & Causal Engine"])


class EventChange(BaseModel):
    """
    Briefing:
        Represents a field-level delta transition within an event envelope.

    Reason:
        Retains both the prior base value (what the client observed when making the edit)
        and the new proposed value, enabling three-way merge evaluation and causal auditing.
    """
    # Explanation: Prior state observed by the client (None if creating entity)
    base: Optional[Any] = None
    # Explanation: New target state proposed by the mutation
    new: Any


class EventEnvelopeIn(BaseModel):
    """
    Briefing:
        Pydantic representation of an inbound event envelope generated by a mobile edge node.

    Reason:
        Encapsulates all metadata required to enforce distributed consistency, multi-bearer routing,
        and tamper verification (device sequence number, Lamport version vector, relay hop counter,
        and SHA-256 cryptographic integrity hash).
    """
    # Explanation: Deterministic UUIDv4 generated locally by the originating device
    event_id: str
    # Explanation: Tenant organization identifier
    tenant_id: str
    # Explanation: Entity domain ('incident', 'task', 'route_observation', 'evidence')
    entity_type: str
    # Explanation: UUID of the specific target entity
    entity_id: str
    # Explanation: Action type ('CREATED', 'STATUS_CHANGED', 'NOTE_ADDED', etc.)
    event_type: str
    # Explanation: Dictionary of field-level changes (e.g. {"status": {"base": "OPEN", "new": "BLOCKED"}})
    changes: Dict[str, EventChange]
    # Explanation: User UUID of the responder who authorized the action
    actor_id: str
    # Explanation: Hardware device ID that recorded the observation
    device_id: str
    # Explanation: Monotonically increasing sequence number per device for replay detection
    device_sequence: int
    # Explanation: Physical UTC timestamp when the event occurred in the field
    occurred_at: datetime
    # Explanation: Lamport or vector clock mapping device_id -> logical sequence
    version_vector: Dict[str, int] = {}
    # Explanation: List of UUIDs pointing to uploaded cryptographic photo evidence
    evidence_ids: List[str] = []
    # Explanation: Number of mesh hops traversed prior to reaching this server
    relay_hops: int = 0
    # Explanation: Trace of relaying device IDs along the multi-hop mesh path
    relayed_by_devices: List[str] = []
    # Explanation: Primary physical bearer used ('BLE_MESH', 'WIFI_DIRECT', 'CELLULAR', 'DIRECT')
    initial_bearer: Optional[str] = "DIRECT"
    # Explanation: Schema version of the event format (default 1)
    schema_version: int = 1
    # Explanation: SHA-256 digest computed across payload fields for tamper-evidence
    integrity_hash: str


class SyncPushBatch(BaseModel):
    """
    Briefing:
        Batch container submitted by field nodes during synchronization push.

    Reason:
        Allows field devices to upload accumulated outbox queues in an atomic HTTP transaction.
    """
    # Explanation: Originating device hardware identifier
    device_id: str
    # Explanation: Ordered array of event envelopes to ingest
    events: List[EventEnvelopeIn]


class SyncPushResult(BaseModel):
    """
    Briefing:
        Structured response returned after processing a batch of synchronization events.

    Reason:
        Informs the mobile client which event IDs were accepted (allowing the client to mark
        them as synced in its local outbox), which were identified as duplicates, how many
        conflicts were detected, and provides the server's updated cursor timestamp.
    """
    status: str = "success"
    processed_count: int
    accepted_event_ids: List[str]
    duplicate_event_ids: List[str]
    conflicts_detected: int
    server_cursor: str


class SyncPullResult(BaseModel):
    """
    Briefing:
        Payload returned when a client requests downstream events from the server.

    Reason:
        Supplies incremental events received by other field units, enabling the client
        to update its local SQLite database and advance its replication cursor.
    """
    events: List[Dict[str, Any]]
    next_cursor: str
    has_more: bool


@router.post("/push", response_model=SyncPushResult)
async def push_sync_events(
    batch: SyncPushBatch,
    db: AsyncSession = Depends(get_db),
    current_user: TokenPayload = Depends(get_current_user_token),
):
    """
    Briefing:
        Processes an uploaded batch of offline event envelopes into the server's event ledger.

    Reason:
        1. Guarantees Idempotency: Checks `OperationalEvent` table by `event_id`. Duplicates are
           skipped without error, enabling safe client retries across unreliable links.
        2. Preserves Immutable Audit Trail: Appends accepted events into `OperationalEvent` with
           server-side `received_at` UTC timestamps and cryptographic hashes.
        3. Applies Domain State Materialization:
           - Automatically merges non-conflicting metadata (e.g. appending field notes and photo IDs).
           - Enforces the Causal Safety Freeze: If a status change contradicts verified physical reality
             (e.g. route USABLE vs BLOCKED), it halts automated updates, locks the route to `UNCERTAIN`,
             freezes dependent tasks, logs a system `AuditEntry`, and opens a `ConflictCase`.
        4. Cache Invalidation: Invalidates central dashboard aggregates (`IOCCacheManager`) so commanders
           immediately see fresh field telemetry.

    Parameters:
        batch: `SyncPushBatch` containing the list of envelopes.
        db: Database session.
        current_user: Authenticated JWT claims.

    Returns:
        `SyncPushResult` detailing accepted events, duplicates, and conflict count.
    """
    accepted_ids = []
    duplicate_ids = []
    conflicts_count = 0

    for ev in batch.events:
        # Explanation: Step 1 - Idempotency verification to prevent duplicate event ingestion
        existing_res = await db.execute(
            select(OperationalEvent).where(
                OperationalEvent.event_id == ev.event_id,
                OperationalEvent.tenant_id == current_user.tenant_id,
            )
        )
        if existing_res.scalars().first():
            duplicate_ids.append(ev.event_id)
            continue

        # Explanation: Step 2 - Append immutable operational event record to historical ledger
        op_event = OperationalEvent(
            id=str(uuid.uuid4()),
            tenant_id=current_user.tenant_id,
            event_id=ev.event_id,
            entity_type=ev.entity_type,
            entity_id=ev.entity_id,
            event_type=ev.event_type,
            changes={k: {"base": v.base, "new": v.new} for k, v in ev.changes.items()},
            actor_id=ev.actor_id,
            device_id=ev.device_id,
            device_sequence=ev.device_sequence,
            occurred_at=ev.occurred_at,
            received_at=datetime.now(timezone.utc),
            version_vector=ev.version_vector,
            evidence_ids=ev.evidence_ids,
            integrity_hash=ev.integrity_hash,
        )
        db.add(op_event)
        accepted_ids.append(ev.event_id)

        # Explanation: Step 3 - Domain Entity Materialization & Contradiction Evaluation
        if ev.entity_type == "route_observation":
            route_id = ev.entity_id
            r_res = await db.execute(
                select(RouteObservation).where(
                    RouteObservation.route_identifier == route_id,
                    RouteObservation.tenant_id == current_user.tenant_id,
                )
            )
            route = r_res.scalars().first()
            if not route:
                # Explanation: Lazily instantiate route observation entity if first report
                route = RouteObservation(
                    id=str(uuid.uuid4()),
                    tenant_id=current_user.tenant_id,
                    route_identifier=route_id,
                    status="UNKNOWN",
                    notes=[],
                    photos=[],
                )
                db.add(route)

            # Explanation: Safe Additive Metadata - notes are merged without conflict
            if "notes" in ev.changes:
                new_note = ev.changes["notes"].new
                current_notes = list(route.notes or [])
                if isinstance(new_note, list):
                    current_notes.extend(new_note)
                elif new_note and new_note not in current_notes:
                    current_notes.append(new_note)
                route.notes = current_notes

            # Explanation: Safe Additive Metadata - photographic evidence IDs are accumulated
            if "photos" in ev.changes or ev.evidence_ids:
                current_photos = list(route.photos or [])
                for pid in ev.evidence_ids:
                    if pid not in current_photos:
                        current_photos.append(pid)
                route.photos = current_photos

            # Explanation: Protected Life-Safety Attribute Handling (Route Status)
            if "status" in ev.changes:
                new_status = str(ev.changes["status"].new).upper()
                old_status = str(route.status).upper()

                if old_status not in ["UNKNOWN", "UNCERTAIN"] and old_status != new_status:
                    # Explanation: Concurrency contradiction detected! Trigger safety freeze!
                    conflicts_count += 1
                    
                    # Explanation: Create persistent Conflict Case for human supervisor adjudication
                    conflict_case = ConflictCase(
                        id=str(uuid.uuid4()),
                        tenant_id=current_user.tenant_id,
                        entity_type="route_observation",
                        entity_id=route_id,
                        conflicting_field="status",
                        status="OPEN",
                        claims=[
                            {
                                "actor_id": route.last_reported_by or "prior_responder",
                                "device_id": "prior_device",
                                "value": old_status,
                                "occurred_at": route.last_reported_at.isoformat() if route.last_reported_at else datetime.utcnow().isoformat(),
                            },
                            {
                                "actor_id": ev.actor_id,
                                "device_id": ev.device_id,
                                "value": new_status,
                                "occurred_at": ev.occurred_at.isoformat(),
                                "evidence_ids": ev.evidence_ids,
                            },
                        ],
                        frozen_dependencies=[],
                    )
                    
                    # Explanation: Freeze route into UNCERTAIN state to prevent misleading responders
                    route.status = "UNCERTAIN"
                    route.is_frozen = "TRUE"
                    route.active_conflict_id = conflict_case.id

                    # Explanation: Freeze dependent rescue tasks utilizing this route segment
                    t_res = await db.execute(
                        select(Task).where(
                            Task.route_id == route_id,
                            Task.tenant_id == current_user.tenant_id,
                        )
                    )
                    frozen_task_ids = []
                    for t in t_res.scalars().all():
                        t.is_route_blocked = "TRUE"
                        frozen_task_ids.append(t.id)
                    conflict_case.frozen_dependencies = frozen_task_ids
                    
                    db.add(conflict_case)

                    # Explanation: Protected immutable audit log entry
                    audit = AuditEntry(
                        id=str(uuid.uuid4()),
                        tenant_id=current_user.tenant_id,
                        action="CONFLICT_DETECTED_FREEZE",
                        actor_id="system_conflict_engine",
                        actor_role="SYSTEM",
                        target_entity_type="route_observation",
                        target_entity_id=route_id,
                        previous_state={"status": old_status},
                        new_state={"status": "UNCERTAIN", "conflict_id": conflict_case.id},
                        reason=f"Life-safety contradiction: {old_status} vs {new_status}. Automation frozen.",
                    )
                    db.add(audit)
                else:
                    # Explanation: Non-conflicting status progression applies cleanly
                    route.status = new_status
                    route.last_reported_by = ev.actor_id
                    route.last_reported_at = ev.occurred_at

            await db.flush()

    await db.commit()

    # Explanation: Invalidate cached operational summaries so command dashboards reflect fresh events
    from app.modules.dashboard.router import IOCCacheManager
    IOCCacheManager.invalidate(current_user.tenant_id)

    return SyncPushResult(
        status="success",
        processed_count=len(batch.events),
        accepted_event_ids=accepted_ids,
        duplicate_event_ids=duplicate_ids,
        conflicts_detected=conflicts_count,
        server_cursor=datetime.now(timezone.utc).isoformat(),
    )


@router.get("/pull", response_model=SyncPullResult)
async def pull_sync_events(
    cursor: Optional[str] = None,
    limit: int = 50,
    db: AsyncSession = Depends(get_db),
    current_user: TokenPayload = Depends(get_current_user_token),
):
    """
    Briefing:
        Retrieves an incremental page of downstream operational events newer than a given cursor.

    Reason:
        Allows field devices to efficiently synchronize without downloading the entire database.
        Devices supply their last recorded `cursor` (UTC ISO string). The server queries
        `received_at > cursor` ordered chronologically, returning up to `limit` events.

    Parameters:
        cursor: Optional ISO-8601 UTC timestamp representing client's current sync watermark.
        limit: Maximum number of events to return in a single page (default 50).
        db: Database session.
        current_user: Authenticated JWT claims.

    Returns:
        `SyncPullResult` containing event list, `next_cursor`, and `has_more` boolean.
    """
    query = select(OperationalEvent).where(
        OperationalEvent.tenant_id == current_user.tenant_id
    )
    if cursor:
        try:
            dt = datetime.fromisoformat(cursor)
            query = query.where(OperationalEvent.received_at > dt)
        except Exception:
            pass

    query = query.order_by(OperationalEvent.received_at.asc()).limit(limit)
    result = await db.execute(query)
    events = result.scalars().all()

    formatted = [
        {
            "event_id": e.event_id,
            "entity_type": e.entity_type,
            "entity_id": e.entity_id,
            "event_type": e.event_type,
            "changes": e.changes,
            "actor_id": e.actor_id,
            "device_id": e.device_id,
            "occurred_at": e.occurred_at.isoformat(),
            "received_at": e.received_at.isoformat(),
            "evidence_ids": e.evidence_ids,
            "integrity_hash": e.integrity_hash,
        }
        for e in events
    ]

    next_cur = events[-1].received_at.isoformat() if events else (cursor or datetime.now(timezone.utc).isoformat())

    return SyncPullResult(
        events=formatted,
        next_cursor=next_cur,
        has_more=len(events) == limit,
    )


# ---------------------------------------------------------------------------
# Omni-Bearer Mesh Protocol: BLE 5.0 GATT MTU Packet Framing & Reassembly
# (Spec: docs/30_MULTI_BEARER_BLUETOOTH_WIFI_CELLULAR_MESH_SPEC.md)
# ---------------------------------------------------------------------------

class MeshFrame(BaseModel):
    """
    Briefing:
        Data model for an individual BLE/radio mesh packet frame.

    Reason:
        Standard Bluetooth Low Energy (BLE) 5.0 GATT connections support an ATT MTU safe payload
        limit of approximately 496 bytes. Larger disaster data envelopes (such as JSON task models
        or telemetry summaries) must be sliced into numbered chunks, tagged with CRC32 checksums,
        and reassembled by peer nodes.
    """
    # Explanation: Master packet identifier common across all chunks of a single message
    packet_id: str
    # Explanation: Zero-indexed position of this chunk within the complete sequence
    chunk_index: int
    # Explanation: Total count of chunks composing the full payload
    total_chunks: int
    # Explanation: Base64-encoded raw binary data of this slice
    chunk_payload_base64: str
    # Explanation: Text representation of payload slice (or '<binary>' if non-UTF8)
    chunk_payload_text: str
    # Explanation: Size of this chunk in raw bytes
    chunk_bytes: int
    # Explanation: 8-character hex CRC32 checksum of this chunk's raw bytes
    crc32: str
    # Explanation: Number of peer-to-peer radio hops this frame has traversed
    hop_count: int = 1


class MeshPacketizeRequest(BaseModel):
    """
    Briefing:
        Request payload submitted to slice a JSON or string message into BLE mesh frames.
    """
    payload: Any
    max_mtu_bytes: int = 496  # BLE 5.0 ATT MTU safe limit
    bearer: str = "BLE_5.0_GATT"
    source_device_id: str = "node-citizen-01"
    target_device_id: str = "hub-command-00"


class MeshPacketizeResponse(BaseModel):
    """
    Briefing:
        Response returning the array of generated `MeshFrame` records.
    """
    packet_id: str
    total_original_bytes: int
    total_frames: int
    max_frame_bytes: int
    bearer: str
    frames: List[MeshFrame]


class MeshReassembleRequest(BaseModel):
    """
    Briefing:
        Request payload containing an unordered collection of `MeshFrame` objects to reassemble.
    """
    frames: List[MeshFrame]


class MeshReassembleResponse(BaseModel):
    """
    Briefing:
        Response returning the reassembled payload, verification status, and cryptographic digests.
    """
    packet_id: str
    status: str
    received_frames: int
    total_frames: int
    reassembled_payload: str
    integrity_hash_sha256: str
    crc32_verified: bool


@router.post("/mesh/packetize", response_model=MeshPacketizeResponse)
async def packetize_mesh_payload(
    req: MeshPacketizeRequest,
    current_user: TokenPayload = Depends(get_current_user_token),
):
    """
    Briefing:
        Slices an arbitrary JSON or text operational payload into <= 496-byte BLE GATT MTU frames.

    Reason:
        Enforces the Omni-Bearer Framing invariant for zero-connectivity BLE gossip relays.
        Computes 32-bit cyclic redundancy check (CRC32) digests on each slice so receiving
        radios can detect bit flips caused by radio frequency interference before reassembly.

    Parameters:
        req: `MeshPacketizeRequest` specifying payload, MTU limit, and bearer type.
        current_user: Authenticated JWT claims.

    Returns:
        `MeshPacketizeResponse` containing packet ID and sequenced frame list.
    """
    if isinstance(req.payload, (dict, list)):
        raw_bytes = json.dumps(req.payload, separators=(",", ":")).encode("utf-8")
    else:
        raw_bytes = str(req.payload).encode("utf-8")

    packet_id = f"pkt-{uuid.uuid4().hex[:12]}"
    max_chunk_size = max(64, min(req.max_mtu_bytes, 496))

    chunks = [raw_bytes[i : i + max_chunk_size] for i in range(0, len(raw_bytes), max_chunk_size)]
    if not chunks:
        chunks = [b""]

    total_chunks = len(chunks)
    frames = []

    for idx, chunk in enumerate(chunks):
        crc = f"{zlib.crc32(chunk) & 0xFFFFFFFF:08x}"
        chunk_b64 = base64.b64encode(chunk).decode("ascii")
        try:
            chunk_text = chunk.decode("utf-8", errors="replace")
        except Exception:
            chunk_text = "<binary>"

        frames.append(
            MeshFrame(
                packet_id=packet_id,
                chunk_index=idx,
                total_chunks=total_chunks,
                chunk_payload_base64=chunk_b64,
                chunk_payload_text=chunk_text,
                chunk_bytes=len(chunk),
                crc32=crc,
                hop_count=1,
            )
        )

    return MeshPacketizeResponse(
        packet_id=packet_id,
        total_original_bytes=len(raw_bytes),
        total_frames=total_chunks,
        max_frame_bytes=max_chunk_size,
        bearer=req.bearer,
        frames=frames,
    )


@router.post("/mesh/reassemble", response_model=MeshReassembleResponse)
async def reassemble_mesh_payload(
    req: MeshReassembleRequest,
    current_user: TokenPayload = Depends(get_current_user_token),
):
    """
    Briefing:
        Reassembles potentially out-of-order BLE GATT MTU frames into the complete original payload.

    Reason:
        Validates the CRC32 integrity tag on each individual frame. Once all chunks (0 through N-1)
        are present and verified, concatenates the binary buffers and calculates the overall
        SHA-256 integrity digest to prove no bitrot or tampering occurred during mesh gossip.

    Parameters:
        req: `MeshReassembleRequest` containing frames received over radio.
        current_user: Authenticated JWT claims.

    Returns:
        `MeshReassembleResponse` with status ('REASSEMBLED_VERIFIED', 'CORRUPTED', or 'INCOMPLETE')
        and decoded payload text.

    Raises:
        HTTPException(400): If the submitted frame list is empty.
    """
    if not req.frames:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cannot reassemble empty frame list",
        )

    packet_id = req.frames[0].packet_id
    total_expected = req.frames[0].total_chunks

    # Explanation: Group by chunk_index to de-duplicate multiple mesh gossip copies
    seen_indices = {}
    crc_all_valid = True

    for frame in req.frames:
        if frame.packet_id != packet_id:
            continue
        try:
            chunk_bytes = base64.b64decode(frame.chunk_payload_base64)
            computed_crc = f"{zlib.crc32(chunk_bytes) & 0xFFFFFFFF:08x}"
            if computed_crc.lower() != frame.crc32.lower():
                crc_all_valid = False
            seen_indices[frame.chunk_index] = chunk_bytes
        except Exception:
            crc_all_valid = False

    received_count = len(seen_indices)
    if received_count < total_expected or not crc_all_valid:
        status_str = "CORRUPTED" if not crc_all_valid else "INCOMPLETE"
        return MeshReassembleResponse(
            packet_id=packet_id,
            status=status_str,
            received_frames=received_count,
            total_frames=total_expected,
            reassembled_payload="",
            integrity_hash_sha256="",
            crc32_verified=crc_all_valid,
        )

    # Explanation: Assemble chunks in strict sequential order from index 0 to total_expected - 1
    assembled_bytes = bytearray()
    for i in range(total_expected):
        if i in seen_indices:
            assembled_bytes.extend(seen_indices[i])
        else:
            return MeshReassembleResponse(
                packet_id=packet_id,
                status="MISSING_CHUNKS",
                received_frames=received_count,
                total_frames=total_expected,
                reassembled_payload="",
                integrity_hash_sha256="",
                crc32_verified=False,
            )

    payload_str = assembled_bytes.decode("utf-8", errors="replace")
    sha256_hash = hashlib.sha256(assembled_bytes).hexdigest()

    return MeshReassembleResponse(
        packet_id=packet_id,
        status="REASSEMBLED_VERIFIED",
        received_frames=received_count,
        total_frames=total_expected,
        reassembled_payload=payload_str,
        integrity_hash_sha256=sha256_hash,
        crc32_verified=True,
    )
