"""
ShiVi Audit Ledger & Operational Traceability Data Models
=========================================================

Briefing:
    Defines the dual-ledger persistence models for the ShiVi platform:
    1. `OperationalEvent`: The distributed event-sourcing ledger storing raw, immutable
       event envelopes generated by mobile edge nodes during offline synchronization.
    2. `AuditEntry`: The administrative and human-in-the-loop compliance ledger recording
       every supervisor triage, conflict adjudication, task dispatch, and mission verification.

Reason:
    During disaster investigations and post-incident reviews, questions inevitably arise:
    "Who declared the bridge closed?", "Why was the rescue boat sent to Sector 4 instead of Sector 2?",
    "Did radio messages get delayed or tampered with?".
    These two ledgers guarantee:
    - Zero Tampering: Every operational event retains its originating client timestamp,
      device sequence counter, version vector, and SHA-256 cryptographic digest.
    - Accountability: Every state mutation by human commanders records previous state,
      new state, actor role, and mandatory operational justification.
    - Reconstruction: Entire disaster timelines can be replayed chronologically from scratch.
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, JSON, Text
from app.core.database import Base


class OperationalEvent(Base):
    """
    Briefing:
        SQLAlchemy ORM model representing an immutable distributed operational event.

    Reason:
        The backbone of ShiVi's event-sourcing architecture. Captures every field observation,
        status change, and data mutation emitted by edge nodes, preserving cryptographic hashes
        and causal Lamport clocks for deterministic replay.
    """
    __tablename__ = "operational_events"

    # Explanation: Primary key UUID of the database record
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Explanation: Multi-tenant jurisdictional isolation key
    tenant_id = Column(String, ForeignKey("tenants.id"), nullable=False)
    
    # Explanation: Globally unique event UUID generated by originating client device
    event_id = Column(String, unique=True, nullable=False, index=True)
    
    # Explanation: Target entity category ('incident', 'task', 'route_observation', 'evidence')
    entity_type = Column(String, nullable=False)
    
    # Explanation: Unique identifier of the specific target entity
    entity_id = Column(String, nullable=False, index=True)
    
    # Explanation: Semantic event type ('CREATED', 'STATUS_CHANGED', 'NOTE_ADDED', etc.)
    event_type = Column(String, nullable=False)
    
    # Explanation: JSON payload containing field-level base and new value transitions
    changes = Column(JSON, nullable=False)
    
    # Explanation: User UUID of the actor who performed the action
    actor_id = Column(String, nullable=False)
    
    # Explanation: Hardware device ID where the event was recorded
    device_id = Column(String, nullable=False)
    
    # Explanation: Monotonic sequence counter emitted by the device for replay protection
    device_sequence = Column(Integer, nullable=False)
    
    # Explanation: Physical time when the event occurred in the field (from client clock)
    occurred_at = Column(DateTime, nullable=False)
    
    # Explanation: UTC timestamp when the server received and ingested the event
    received_at = Column(DateTime, default=datetime.utcnow)
    
    # Explanation: Vector clock capturing causal dependencies across peer nodes
    version_vector = Column(JSON, default=dict)
    
    # Explanation: Array of evidence UUIDs attached to this event
    evidence_ids = Column(JSON, default=list)
    
    # Explanation: SHA-256 cryptographic digest proving content integrity
    integrity_hash = Column(String, nullable=False)


class AuditEntry(Base):
    """
    Briefing:
        SQLAlchemy ORM model representing a high-level administrative or supervisor audit record.

    Reason:
        Records human-in-the-loop decisions (conflict adjudications, manual priority overrides,
        task verifications). Retains previous and new state JSON snapshots alongside the mandatory
        operational justification entered by the supervisor.
    """
    __tablename__ = "audit_entries"

    # Explanation: Primary key UUID of the audit entry
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Explanation: Multi-tenant jurisdictional isolation key
    tenant_id = Column(String, ForeignKey("tenants.id"), nullable=False)
    
    # Explanation: Formal action tag (e.g., 'CONFLICT_ADJUDICATED_RESOLVED', 'INCIDENT_TRIAGED')
    action = Column(String, nullable=False)
    
    # Explanation: User UUID of the supervisor or system engine executing the action
    actor_id = Column(String, nullable=False)
    
    # Explanation: Role of the actor ('SUPERVISOR', 'ADMIN', 'SYSTEM')
    actor_role = Column(String, nullable=False)
    
    # Explanation: Category of entity modified ('incident', 'task', 'route_observation')
    target_entity_type = Column(String, nullable=False)
    
    # Explanation: Target entity primary UUID
    target_entity_id = Column(String, nullable=False)
    
    # Explanation: State snapshot prior to mutation
    previous_state = Column(JSON, nullable=True)
    
    # Explanation: State snapshot following mutation
    new_state = Column(JSON, nullable=True)
    
    # Explanation: Written justification or operational rationale
    reason = Column(Text, nullable=True)
    
    # Explanation: Server UTC timestamp when action was recorded
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    # Explanation: Network client IP address of the caller
    ip_address = Column(String, nullable=True)
